default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cmbc_bank_api_development

test:
  <<: *default
  database: cmbc_bank_api_test

production:
  <<: *default
  database: cmbc_bank_api_production
  username: cmbc_bank_api
  password: <%= ENV["CMBC_BANK_API_DATABASE_PASSWORD"] %>
