default: &default
  adapter: postgresql
  encoding: unicode
  host: cmbc-bank-db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: cmbc_bank_api_development

test:
  <<: *default
  database: cmbc_bank_api_test

production:
  <<: *default
  database: cmbc_bank_api_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
